language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.0.1-amd64.deb && sudo service elasticsearch restart

before_script:
  - sleep 10

script:
  - python test.py
