language: python

services:
  - docker

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - docker run --rm --detach --publish 9200:9200 --env "discovery.type=single-node" -e path.repo=/tmp -e "repositories.url.allowed_urls=http://*" -e node.attr.testattr=test  -e node.name=test  --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch:7.4.0

before_script:
  - sleep 10

script:
  - python test.py
